/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmdataframe_free: (a: number, b: number) => void;
export const wasmdataframe_new: () => number;
export const wasmdataframe_fromObject: (a: any) => [number, number, number];
export const wasmdataframe_rowCount: (a: number) => number;
export const wasmdataframe_columnCount: (a: number) => number;
export const wasmdataframe_columnNames: (a: number) => [number, number];
export const wasmdataframe_filterGt: (a: number, b: number, c: number, d: any) => [number, number, number];
export const wasmdataframe_groupBy: (a: number, b: number, c: number) => [number, number, number];
export const wasmdataframe_addSeries: (a: number, b: number, c: number, d: number) => [number, number];
export const wasmdataframe_getColumn: (a: number, b: number, c: number) => number;
export const wasmdataframe_toJson: (a: number) => [number, number];
export const __wbg_wasmseries_free: (a: number, b: number) => void;
export const wasmseries_new: (a: number, b: number, c: number, d: number) => [number, number, number];
export const wasmseries_length: (a: number) => number;
export const wasmseries_name: (a: number) => [number, number];
export const wasmseries_sum: (a: number) => [number, number];
export const wasmseries_add: (a: number, b: number) => [number, number, number];
export const wasmseries_multiply: (a: number, b: number) => [number, number, number];
export const __wbg_wasmgroupeddataframe_free: (a: number, b: number) => void;
export const wasmgroupeddataframe_sum: (a: number) => [number, number, number];
export const wasmgroupeddataframe_mean: (a: number) => [number, number, number];
export const simdAddF64: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const simdSumF64: (a: number, b: number) => number;
export const __wbg_wasmvalue_free: (a: number, b: number) => void;
export const __wbg_wasmexpr_free: (a: number, b: number) => void;
export const __wbindgen_export_0: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_start: () => void;
